// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRAvzGUl0pxjwmWvSQ7y6TpUNVjbaI0w0',
    appId: '1:835243323059:web:dda807d5d0d398583b8ac6',
    messagingSenderId: '835243323059',
    projectId: 'trigger-83429',
    authDomain: 'trigger-83429.firebaseapp.com',
    storageBucket: 'trigger-83429.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyk7kYr_cYZRO68-k4GOshGyTU2yvV94Q',
    appId: '1:835243323059:android:9707c45e8469edf93b8ac6',
    messagingSenderId: '835243323059',
    projectId: 'trigger-83429',
    storageBucket: 'trigger-83429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwSb3bi1paGBOk2YMKyRKW5EV-QSyu74',
    appId: '1:835243323059:ios:2198f0a1ff7893f83b8ac6',
    messagingSenderId: '835243323059',
    projectId: 'trigger-83429',
    storageBucket: 'trigger-83429.firebasestorage.app',
    iosBundleId: 'com.example.trigger',
  );
}
